#!/bin/bash


abs_path="$(cd "$(dirname "$0")" && pwd)"

export PATH="${abs_path}:${PATH}"


command="$1"

if [ -z "$command" ]; then
    echo  "$(jsenv-help)" >&2 
else
    command_path="$(command -v "jsenv-$command" || true)"
    if [ -z "$command_path" ]; then
        echo "jsenv: no such command $command" >&2
        exit 1
    fi

    shift 1
    exec "$command_path" "$@"
fi





